/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LaserRouteImport } from './routes/laser'
import { Route as FacialRouteImport } from './routes/facial'
import { Route as BotoxRouteImport } from './routes/botox'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LaserRoute = LaserRouteImport.update({
  id: '/laser',
  path: '/laser',
  getParentRoute: () => rootRouteImport,
} as any)
const FacialRoute = FacialRouteImport.update({
  id: '/facial',
  path: '/facial',
  getParentRoute: () => rootRouteImport,
} as any)
const BotoxRoute = BotoxRouteImport.update({
  id: '/botox',
  path: '/botox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/facial': typeof FacialRoute
  '/laser': typeof LaserRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/facial': typeof FacialRoute
  '/laser': typeof LaserRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/facial': typeof FacialRoute
  '/laser': typeof LaserRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/botox' | '/facial' | '/laser' | '/services' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/botox' | '/facial' | '/laser' | '/services' | '/team'
  id: '__root__' | '/' | '/botox' | '/facial' | '/laser' | '/services' | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotoxRoute: typeof BotoxRoute
  FacialRoute: typeof FacialRoute
  LaserRoute: typeof LaserRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laser': {
      id: '/laser'
      path: '/laser'
      fullPath: '/laser'
      preLoaderRoute: typeof LaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facial': {
      id: '/facial'
      path: '/facial'
      fullPath: '/facial'
      preLoaderRoute: typeof FacialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/botox': {
      id: '/botox'
      path: '/botox'
      fullPath: '/botox'
      preLoaderRoute: typeof BotoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotoxRoute: BotoxRoute,
  FacialRoute: FacialRoute,
  LaserRoute: LaserRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
