/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RejuvenationRouteImport } from './routes/rejuvenation'
import { Route as PrpRouteImport } from './routes/prp'
import { Route as LaserRouteImport } from './routes/laser'
import { Route as HairRouteImport } from './routes/hair'
import { Route as FacialRouteImport } from './routes/facial'
import { Route as EndoliftRouteImport } from './routes/endolift'
import { Route as BotoxRouteImport } from './routes/botox'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RejuvenationRoute = RejuvenationRouteImport.update({
  id: '/rejuvenation',
  path: '/rejuvenation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrpRoute = PrpRouteImport.update({
  id: '/prp',
  path: '/prp',
  getParentRoute: () => rootRouteImport,
} as any)
const LaserRoute = LaserRouteImport.update({
  id: '/laser',
  path: '/laser',
  getParentRoute: () => rootRouteImport,
} as any)
const HairRoute = HairRouteImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => rootRouteImport,
} as any)
const FacialRoute = FacialRouteImport.update({
  id: '/facial',
  path: '/facial',
  getParentRoute: () => rootRouteImport,
} as any)
const EndoliftRoute = EndoliftRouteImport.update({
  id: '/endolift',
  path: '/endolift',
  getParentRoute: () => rootRouteImport,
} as any)
const BotoxRoute = BotoxRouteImport.update({
  id: '/botox',
  path: '/botox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/endolift': typeof EndoliftRoute
  '/facial': typeof FacialRoute
  '/hair': typeof HairRoute
  '/laser': typeof LaserRoute
  '/prp': typeof PrpRoute
  '/rejuvenation': typeof RejuvenationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/endolift': typeof EndoliftRoute
  '/facial': typeof FacialRoute
  '/hair': typeof HairRoute
  '/laser': typeof LaserRoute
  '/prp': typeof PrpRoute
  '/rejuvenation': typeof RejuvenationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/botox': typeof BotoxRoute
  '/endolift': typeof EndoliftRoute
  '/facial': typeof FacialRoute
  '/hair': typeof HairRoute
  '/laser': typeof LaserRoute
  '/prp': typeof PrpRoute
  '/rejuvenation': typeof RejuvenationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/botox'
    | '/endolift'
    | '/facial'
    | '/hair'
    | '/laser'
    | '/prp'
    | '/rejuvenation'
    | '/services'
    | '/sitemap.xml'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/botox'
    | '/endolift'
    | '/facial'
    | '/hair'
    | '/laser'
    | '/prp'
    | '/rejuvenation'
    | '/services'
    | '/sitemap.xml'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/botox'
    | '/endolift'
    | '/facial'
    | '/hair'
    | '/laser'
    | '/prp'
    | '/rejuvenation'
    | '/services'
    | '/sitemap.xml'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotoxRoute: typeof BotoxRoute
  EndoliftRoute: typeof EndoliftRoute
  FacialRoute: typeof FacialRoute
  HairRoute: typeof HairRoute
  LaserRoute: typeof LaserRoute
  PrpRoute: typeof PrpRoute
  RejuvenationRoute: typeof RejuvenationRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejuvenation': {
      id: '/rejuvenation'
      path: '/rejuvenation'
      fullPath: '/rejuvenation'
      preLoaderRoute: typeof RejuvenationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prp': {
      id: '/prp'
      path: '/prp'
      fullPath: '/prp'
      preLoaderRoute: typeof PrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laser': {
      id: '/laser'
      path: '/laser'
      fullPath: '/laser'
      preLoaderRoute: typeof LaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair': {
      id: '/hair'
      path: '/hair'
      fullPath: '/hair'
      preLoaderRoute: typeof HairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facial': {
      id: '/facial'
      path: '/facial'
      fullPath: '/facial'
      preLoaderRoute: typeof FacialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endolift': {
      id: '/endolift'
      path: '/endolift'
      fullPath: '/endolift'
      preLoaderRoute: typeof EndoliftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/botox': {
      id: '/botox'
      path: '/botox'
      fullPath: '/botox'
      preLoaderRoute: typeof BotoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotoxRoute: BotoxRoute,
  EndoliftRoute: EndoliftRoute,
  FacialRoute: FacialRoute,
  HairRoute: HairRoute,
  LaserRoute: LaserRoute,
  PrpRoute: PrpRoute,
  RejuvenationRoute: RejuvenationRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
